dist: trusty
sudo: false

language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE="cujo.settings.test"

install:
  - pip install --editable .[tests]
  - npm install -g gulp
  - npm install

before_script:
  - psql -c "CREATE DATABASE test_cujo;" -U postgres
  - gulp

script:
  - tox
