dist: trusty
sudo: false

language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"

env:
  - DJANGO_SETTINGS_MODULE='cujo.settings.test'

install:
  - pip install -r requirements.txt
  - npm install -g gulp
  - npm install

before_script:
  - psql -c "CREATE DATABASE test_cujo;" -U postgres
  - psql -c "CREATE USER django_tester PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER django_tester CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE test_cujo to django_tester;" -U postgres

script:
  - gulp
  - python manage.py test
